login:
    pattern: /login
    defaults:  { _controller: AltageUserBundle:Security:login }

login_check:
    pattern:  /login_check
    
logout:
    pattern: /logout
    
_AdminAddUser:
    pattern:  /app/admin/add_user
    defaults: { _controller: AltageUserBundle:Admin/AdminUser:AddUser }

_AdminDispUser:
    pattern:  /app/admin/disp_user
    defaults: { _controller: AltageUserBundle:Admin/AdminUser:DispUser }

_AdminEditUser:
    pattern:  /app/admin/edit_user/{id}
    defaults: { _controller: AltageUserBundle:Admin/AdminUser:EditUser }
